# /********************************************************************************
# * Copyright (c) 2022 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/
# Note: The strings under "comm" must be concatenated to 15 characters, otherwise it will not match
process_names:
  - name: "{{.ExeBase}}"
    comm: 
    - qemu-system-aar
    - qemu-system-x86
